general:
    columnNames: ["INDEX NO", "NAME", "GENDER", "UACE YEAR", "CODE", "DISTRICT", "COURSE CODE", "COURSE NAME"]
    columnNames2: ["APPLICATION NO", "INDEX NO", "NAME", "GENDER", "UACE YEAR", "CODE", "DISTRICT", "COURSE CODE", "COURSE NAME", "TOTAL WEIGHT"]
    saved_file: 'private.csv'